# Project 4 -- Lukas Anell

In [1]:
# /anvil/projects/tdm/data/titanic/titanic.csv

## Question 1

In [2]:
import pandas as pd

In [3]:
myDF = pd.read_csv("/anvil/projects/tdm/data/titanic/titanic.csv")
myDF.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
myDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
myDF.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
my_names = myDF["Name"]
my_names.tolist()[:5]

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry']

In [7]:
my_ages = myDF["Age"]
my_ages.tolist()[:5]

[22.0, 38.0, 26.0, 35.0, 35.0]

In [8]:
combined_names_ages = my_names.tolist() + my_ages.tolist()
combined_names_ages[:5]

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry']

In [9]:
name_age_df = myDF[["Name", "Age"]]
name_age_df.head()

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [10]:
name_age_df.shape

(891, 2)

For creating a single list, I wasn't sure if the instructions want me to just concatenate them or to line up the data together. I just concatenated them, but it wouldn't be too hard to make tuples for the data.

1.1: See above.

1.2: See above.

1.3: See above.

## Question 2

In [11]:
print(my_names.shape)
print(my_names.dtype)
print(my_names[44])

(891,)
object
Devaney, Miss. Margaret Delia

In [12]:
print(my_ages.shape)
print(my_ages.dtype)
print(my_ages[44])

(891,)
float64
19.0

In [13]:
my_selection = my_ages < 20

In [14]:
my_result = my_names[my_selection] + ", age " + my_ages[my_selection].astype(str)
my_result

7             Palsson, Master. Gosta Leonard, age 2.0
9       Nasser, Mrs. Nicholas (Adele Achem), age 14.0
10           Sandstrom, Miss. Marguerite Rut, age 4.0
14     Vestrom, Miss. Hulda Amanda Adolfina, age 14.0
16                      Rice, Master. Eugene, age 2.0
                            ...
855              Aks, Mrs. Sam (Leah Rosen), age 18.0
869          Johnson, Master. Harold Theodor, age 4.0
875        Najib, Miss. Adele Kiamie "Jane", age 15.0
877                    Petroff, Mr. Nedelio, age 19.0
887            Graham, Miss. Margaret Edith, age 19.0
Length: 164, dtype: object

2.1: Miss Margaret Delia Devaney was the 45th passenger and they were 19 years old

2.2: my_names contains objects. my_ages contains float64s

2.3: See above.

## Question 3

In [18]:
myDF["Survived"].head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [19]:
myDF["Passenger_Class"] = pd.Categorical(
    myDF["Pclass"],
    categories=[1, 2, 3],
    ordered=True
).rename_categories(["First Class", "Second Class", "Third Class"])

myDF["Passenger_Class"].head()

0    Third Class
1    First Class
2    Third Class
3    First Class
4    Third Class
Name: Passenger_Class, dtype: category
Categories (3, object): ['First Class' < 'Second Class' < 'Third Class']

In [21]:
myDF["Status"] = myDF["Survived"].map({0: "Dead", 1: "Alive"})
myDF["Status"].head()

0     Dead
1    Alive
2    Alive
3    Alive
4     Dead
Name: Status, dtype: object

In [23]:
myDF["Status"].value_counts()

Status
Dead     549
Alive    342
Name: count, dtype: int64

In [22]:
myDF["Combined"] = myDF["Status"].str.cat(myDF["Sex"], sep=", ")
myDF["Combined"].head()

0       Dead, male
1    Alive, female
2    Alive, female
3    Alive, female
4       Dead, male
Name: Combined, dtype: object

In [24]:
myDF["Combined"].value_counts()

Combined
Dead, male       468
Alive, female    233
Alive, male      109
Dead, female      81
Name: count, dtype: int64

I don't really like how you can just do `.str` on the columns and it'll make every entry into a String. It seems very counterintuitive and I'd prefer a better name or something different from what it is now.

3.1: See above.

3.2: See above.

3.3: I used `.cat()` with comma separators.

## Question 4

In [34]:
old_ages = [61, 62, 63, 64, 65, 66, 70, 70.5, 71, 74, 80]
old = myDF["Age"][myDF["Age"].isin(old_ages)]
old.head()

33     66.0
54     65.0
96     71.0
116    70.5
170    61.0
Name: Age, dtype: float64

In [44]:
old.value_counts()

Age
62.0    4
61.0    3
65.0    3
70.0    2
71.0    2
63.0    2
64.0    2
66.0    1
70.5    1
80.0    1
74.0    1
Name: count, dtype: int64

In [49]:
my_list1 = myDF["Age"][myDF["Age"] <= 10]
my_list1.sort_values(ascending=True).head()

803    0.42
755    0.67
644    0.75
469    0.75
78     0.83
Name: Age, dtype: float64

In [50]:
my_list2 = myDF["Age"][(myDF["Age"] > 10) & (myDF["Age"] <= 60)]
my_list2.sort_values(ascending=False).head()

694    60.0
684    60.0
587    60.0
366    60.0
94     59.0
Name: Age, dtype: float64

In [55]:
people = my_list1.tolist() + my_list2.tolist()
people[:5]

[2.0, 4.0, 2.0, 8.0, 3.0]

In [56]:
myDF["Age"].sort_values(ascending=False).head()

630    80.0
851    74.0
493    71.0
96     71.0
116    70.5
Name: Age, dtype: float64

When sorting my_list2, I thought I'd be able to do the chained comparison operators python has, but it didn't work for some reason. `10 < myDF["Age"] <= 60`.

4.1: The youngest was 0.42 years old. The oldest was 80 years old.

4.2: See above.

4.3: See above.

## Question 5

In [79]:
children = myDF["Age"][myDF["Age"] <= 20]
print(children.value_counts().head())
print(min(children))
print(max(children))

Age
18.0    26
19.0    25
16.0    17
20.0    15
17.0    13
Name: count, dtype: int64
0.42
20.0

In [69]:
young = myDF["Age"][(myDF["Age"] > 20) & (myDF["Age"] <= 40)]
print(young.value_counts().head())
print(min(young))
print(max(young))

Age
24.0    30
22.0    27
30.0    25
28.0    25
21.0    24
Name: count, dtype: int64
20.5
40.0

In [73]:
adult = myDF["Age"][(myDF["Age"] > 40) & (myDF["Age"] <= 60)]
print(adult.value_counts().head())
print(min(adult))
print(max(adult))

Age
42.0    13
45.0    12
50.0    10
48.0     9
44.0     9
Name: count, dtype: int64
40.5
60.0

In [83]:
import numpy as np

myDF["AgeGroup"] = ""
myDF.loc[myDF["Age"].isin(children), "AgeGroup"] = "Children"
myDF.loc[myDF["Age"].isin(young), "AgeGroup"] = "Young"
myDF.loc[myDF["Age"].isin(adult), "AgeGroup"] = "Adult"
myDF.loc[myDF["Age"].isin(old), "AgeGroup"] = "Old"
myDF["AgeGroup"].value_counts()

AgeGroup
Young       385
Children    179
            177
Adult       128
Old          22
Name: count, dtype: int64

In [82]:
ct = pd.crosstab(myDF["AgeGroup"], myDF["Combined"])
ct

Combined  Alive, female  Alive, male  Dead, female  Dead, male
AgeGroup
                     36           16            17         108
Adult                34           16            11          67
Children             53           29            24          73
Old                   3            2             0          17
Young               107           46            29         203

I'm a bit confused about how to get value_counts of the children, young, adult lists because lists aren't pandas objects so value_counts() can't be called on them? I decided to just use the myDF columns like we did before to get the ranges so I can do value_counts().
I'm also getting an error saying the Value "Children" has dtype incompatible with float64, but I was able to fix it by setting the AgeGroup column's default value to an empty String.

5.1: See above.

5.2: See above.

5.3: See above.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.

https://www.purdue.edu/odos/osrr/honor-pledge/